package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type structInfo struct {
	Name string
	Type *ast.StructType
	Fset *token.FileSet
}

type pkgInfo struct {
	Name    string
	Structs []structInfo
}

// reset утилита
func main() {
	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "getwd error: %v\n", err)
		os.Exit(1)
	}

	pkgs := map[string]*pkgInfo{}

	err = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			base := filepath.Base(path)
			if base == ".git" || base == "vendor" || (base == "reset" && filepath.Base(filepath.Dir(path)) == "cmd") {
				return filepath.SkipDir
			}
			processDir(path, pkgs)
		}

		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "walk error: %v\n", err)
		os.Exit(1)
	}

	for dir, info := range pkgs {
		if len(info.Structs) == 0 {
			continue
		}
		if err := generateResetFile(dir, info); err != nil {
			fmt.Fprintf(os.Stderr, "generate file for %s: %v\n", dir, err)
			os.Exit(1)
		}
	}
}

func processDir(dir string, pkgs map[string]*pkgInfo) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}

	var goFiles []os.DirEntry
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") {
			continue
		}
		if strings.HasSuffix(name, "_test.go") || name == "reset.gen.go" {
			continue
		}
		goFiles = append(goFiles, e)
	}
	if len(goFiles) == 0 {
		return
	}

	fset := token.NewFileSet()
	var pkgName string

	for _, e := range goFiles {
		filename := filepath.Join(dir, e.Name())
		file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "parse file %s: %v\n", filename, err)
			continue
		}

		if pkgName == "" {
			pkgName = file.Name.Name
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if !hasGenerateResetComment(genDecl.Doc, typeSpec.Doc) {
					continue
				}

				info, ok := pkgs[dir]
				if !ok {
					info = &pkgInfo{Name: pkgName}
					pkgs[dir] = info
				}

				info.Structs = append(info.Structs, structInfo{
					Name: typeSpec.Name.Name,
					Type: structType,
					Fset: fset,
				})
			}
		}
	}
}

func hasGenerateResetComment(groups ...*ast.CommentGroup) bool {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			if strings.Contains(c.Text, "generate:reset") {
				return true
			}
		}
	}
	return false
}

func generateResetFile(dir string, info *pkgInfo) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package " + info.Name + "\n\n")

	for i, s := range info.Structs {
		if i > 0 {
			buf.WriteString("\n")
		}
		writeResetMethod(&buf, &s)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		// fall back to unformatted source for easier debugging
		src = buf.Bytes()
	}

	filename := filepath.Join(dir, "reset.gen.go")
	return os.WriteFile(filename, src, 0o644)
}

func writeResetMethod(buf *bytes.Buffer, s *structInfo) {
	receiverName := "x"

	fmt.Fprintf(buf, "func (%s *%s) Reset() {\n", receiverName, s.Name)
	fmt.Fprintf(buf, "\tif %s == nil {\n", receiverName)
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n\n")

	if s.Type.Fields != nil {
		for _, field := range s.Type.Fields.List {
			if len(field.Names) == 0 {
				// embedded fields are ignored
				continue
			}
			for _, name := range field.Names {
				if name.Name == "_" {
					continue
				}
				fieldName := name.Name
				writeFieldReset(buf, receiverName, fieldName, field.Type, s.Fset)
			}
		}
	}

	buf.WriteString("}\n")
}

func writeFieldReset(buf *bytes.Buffer, recv, fieldName string, expr ast.Expr, fset *token.FileSet) {
	switch t := expr.(type) {
	case *ast.ArrayType:
		// slice (Len == nil)
		if t.Len == nil {
			fmt.Fprintf(buf, "\t%s.%s = %s.%s[:0]\n", recv, fieldName, recv, fieldName)
		}
	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(%s.%s)\n", recv, fieldName)
	case *ast.StarExpr:
		writePointerFieldReset(buf, recv, fieldName, t.X, fset)
	default:
		writeNonPointerFieldReset(buf, recv, fieldName, expr, fset)
	}
}

func writePointerFieldReset(buf *bytes.Buffer, recv, fieldName string, elem ast.Expr, fset *token.FileSet) {
	switch t := elem.(type) {
	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(buf, "\tif %s.%s != nil {\n", recv, fieldName)
			fmt.Fprintf(buf, "\t\t*%s.%s = (*%s.%s)[:0]\n", recv, fieldName, recv, fieldName)
			fmt.Fprintf(buf, "\t}\n")
		}
	case *ast.MapType:
		fmt.Fprintf(buf, "\tif %s.%s != nil {\n", recv, fieldName)
		fmt.Fprintf(buf, "\t\tclear(*%s.%s)\n", recv, fieldName)
		fmt.Fprintf(buf, "\t}\n")
	case *ast.Ident:
		if zero, ok := builtinZeroValue(t.Name); ok {
			fmt.Fprintf(buf, "\tif %s.%s != nil {\n", recv, fieldName)
			fmt.Fprintf(buf, "\t\t*%s.%s = %s\n", recv, fieldName, zero)
			fmt.Fprintf(buf, "\t}\n")
			return
		}
	default:
		fmt.Fprintf(buf, "\tif %s.%s != nil {\n", recv, fieldName)
		fmt.Fprintf(buf, "\t\tif resetter, ok := any(%s.%s).(interface{ Reset() }); ok {\n", recv, fieldName)
		fmt.Fprintf(buf, "\t\t\tresetter.Reset()\n")
		fmt.Fprintf(buf, "\t\t}\n")
		fmt.Fprintf(buf, "\t}\n")
	}
}

func writeNonPointerFieldReset(buf *bytes.Buffer, recv, fieldName string, expr ast.Expr, fset *token.FileSet) {
	if ident, ok := expr.(*ast.Ident); ok {
		if zero, ok := builtinZeroValue(ident.Name); ok {
			fmt.Fprintf(buf, "\t%s.%s = %s\n", recv, fieldName, zero)
			return
		}
	}

	// try to call Reset on nested structs or types with Reset method
	fmt.Fprintf(buf, "\tif resetter, ok := any(&%s.%s).(interface{ Reset() }); ok {\n", recv, fieldName)
	fmt.Fprintf(buf, "\t\tresetter.Reset()\n")
	fmt.Fprintf(buf, "\t}\n")
}

func builtinZeroValue(typ string) (string, bool) {
	switch typ {
	case "string":
		return `""`, true
	case "bool":
		return "false", true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64",
		"complex64", "complex128",
		"byte", "rune":
		return "0", true
	default:
		return "", false
	}
}
